# Generated by Django 2.2.1 on 2019-08-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('forWhichClazz', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deneme', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1000)),
                ('startDate', models.DateTimeField()),
                ('finishDate', models.DateTimeField()),
                ('location', models.CharField(max_length=1000)),
                ('branch', models.CharField(blank=True, max_length=329, null=True)),
                ('status', models.CharField(blank=True, max_length=329, null=True)),
                ('type', models.CharField(blank=True, max_length=329, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('startDate', models.DateTimeField()),
                ('expireDate', models.DateTimeField()),
                ('durationDay', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportsClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('shortName', models.CharField(max_length=120)),
                ('foundingDate', models.CharField(blank=True, max_length=120, null=True)),
                ('cityHeadShip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.CategoryItem')),
                ('coachs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.Coach')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('branch', models.CharField(blank=True, max_length=329, null=True)),
                ('licenseNo', models.CharField(max_length=255)),
                ('expireDate', models.DateTimeField()),
                ('cityHeadShip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.CategoryItem')),
                ('sportsClub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.SportsClub')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('levelType', models.CharField(blank=True, max_length=329, null=True)),
                ('branch', models.CharField(blank=True, max_length=329, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('startDate', models.DateTimeField()),
                ('expireDate', models.DateTimeField()),
                ('durationDay', models.IntegerField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.CategoryItem')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('punishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.Punishment')),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.Level')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='punishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.Punishment'),
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.Level')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.License')),
                ('punishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.Punishment')),
            ],
        ),
    ]
