# Generated by Django 2.2.1 on 2019-08-22 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('forWhichClazz', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Şehir')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1000)),
                ('startDate', models.DateTimeField()),
                ('finishDate', models.DateTimeField()),
                ('location', models.CharField(max_length=1000)),
                ('branch', models.CharField(blank=True, max_length=329, null=True)),
                ('status', models.CharField(blank=True, max_length=329, null=True)),
                ('type', models.CharField(blank=True, max_length=329, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc', models.CharField(blank=True, max_length=120, null=True)),
                ('height', models.CharField(blank=True, max_length=120, null=True)),
                ('weight', models.CharField(blank=True, max_length=120, null=True)),
                ('birthDate', models.DateField(null=True, verbose_name='Doğum Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('startDate', models.DateTimeField()),
                ('expireDate', models.DateTimeField()),
                ('durationDay', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportsClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('shortName', models.CharField(blank=True, max_length=120, null=True)),
                ('foundingDate', models.CharField(blank=True, max_length=120, null=True)),
                ('clubMail', models.CharField(blank=True, max_length=120, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club/', verbose_name='Kulüp Logo')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('communication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wushu.Communication')),
            ],
        ),
        migrations.CreateModel(
            name='MenuAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('url', models.CharField(blank=True, max_length=120, null=True)),
                ('is_parent', models.BooleanField(default=True)),
                ('is_show', models.BooleanField(default=True)),
                ('fa_icon', models.CharField(blank=True, max_length=120, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wushu.MenuAdmin')),
                ('permission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuadmin', to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('url', models.CharField(blank=True, max_length=120, null=True)),
                ('is_parent', models.BooleanField(default=True)),
                ('is_show', models.BooleanField(default=True)),
                ('fa_icon', models.CharField(blank=True, max_length=120, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wushu.Menu')),
                ('permission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MenuPermission', to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('branch', models.CharField(blank=True, max_length=329, null=True)),
                ('licenseNo', models.CharField(max_length=255)),
                ('expireDate', models.DateTimeField()),
                ('cityHeadShip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.CategoryItem')),
                ('sportsClub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.SportsClub')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('levelType', models.CharField(blank=True, max_length=329, null=True)),
                ('branch', models.CharField(blank=True, max_length=329, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('startDate', models.DateTimeField()),
                ('expireDate', models.DateTimeField()),
                ('durationDay', models.IntegerField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.CategoryItem')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('punishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.Punishment')),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('punishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.Punishment')),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('communication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wushu.Communication')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wushu.Person')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
