# Generated by Django 2.2.4 on 2020-01-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='lisansPhoto',
            field=models.FileField(blank=True, null=True, upload_to='lisans/', verbose_name='Lisans '),
        ),
    ]
