# Generated by Django 2.2.1 on 2019-08-22 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wushu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='punishment',
        ),
        migrations.AddField(
            model_name='coach',
            name='communication',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='wushu.Communication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='person',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='wushu.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
