# Generated by Django 2.2.1 on 2019-08-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0002_auto_20190822_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='branch',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3)], default=1, max_length=128, verbose_name='Cinsiyeti'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Bransş Adı'),
        ),
    ]
