# Generated by Django 2.2.1 on 2019-08-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0003_auto_20190822_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='branch',
            field=models.CharField(choices=[('TAOLU', 'TAOLU'), ('SANDA', 'SANDA'), ('WUSHU', 'WUSHU')], max_length=128, verbose_name='Branş'),
        ),
    ]
