# Generated by Django 2.2.1 on 2019-08-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0008_auto_20190826_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bloodType',
            field=models.CharField(choices=[('AB Rh+', 'AB Rh+'), ('AB Rh-', 'AB Rh-'), ('A Rh+', 'A Rh+'), ('A Rh-', 'A Rh-'), ('B Rh+', 'B Rh+'), ('B Rh-', 'B Rh-'), ('AB Rh+', '0 Rh+'), ('AB Rh+', '0 Rh-')], default='AB Rh+', max_length=128, verbose_name='Cinsiyeti'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın')], default='Erkek', max_length=128, verbose_name='Cinsiyeti'),
        ),
    ]
