# Generated by Django 2.2.1 on 2019-08-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0010_auto_20190826_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='beltFinishDate',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='beltStartDate',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='branch',
        ),
    ]
