# Generated by Django 2.2.1 on 2019-08-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0011_auto_20190826_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bloodType',
            field=models.CharField(choices=[('AB Rh+', 'AB Rh+'), ('AB Rh-', 'AB Rh-'), ('A Rh+', 'A Rh+'), ('A Rh-', 'A Rh-'), ('B Rh+', 'B Rh+'), ('B Rh-', 'B Rh-'), ('AB Rh+', '0 Rh+'), ('AB Rh+', '0 Rh-')], default='AB Rh+', max_length=128, verbose_name='Kan Grubu'),
        ),
    ]
