# Generated by Django 2.2.1 on 2019-08-26 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0014_clubrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportclubuser',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wushu.ClubRole', verbose_name='Üye Rolü'),
            preserve_default=False,
        ),
    ]
