# Generated by Django 2.2.1 on 2019-08-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0017_auto_20190826_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='address',
            field=models.TextField(default=1, verbose_name='Adres'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communication',
            name='phoneNumber',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communication',
            name='phoneNumber2',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communication',
            name='postalCode',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
