# Generated by Django 2.2.1 on 2019-08-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0020_auto_20190830_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='phoneNumber2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='postalCode',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
