# Generated by Django 2.1.2 on 2018-11-14 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ödenen Ücret')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Ödeme Tarihi')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='İsim')),
                ('surname', models.CharField(max_length=120, verbose_name='Soyisim')),
                ('patientNumber', models.CharField(max_length=120, verbose_name='Hasta Kayıt Numarası')),
                ('mobilePhone', models.CharField(max_length=120, verbose_name='Telefon Numarası')),
                ('isActive', models.BooleanField(verbose_name='Aktif')),
                ('email', models.CharField(max_length=120, verbose_name='Email')),
                ('birthDate', models.DateField(null=True, verbose_name='Doğum Tarihi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Hasta',
                'verbose_name_plural': 'Hastalar',
            },
        ),
        migrations.CreateModel(
            name='PayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ödenen Ücret')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Hasta')),
            ],
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threatName', models.CharField(max_length=120, verbose_name='Muayene Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Muayene Ücreti')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Muayene Tarihi')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Muayene',
                'verbose_name_plural': 'Muayeneler',
            },
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Hasta'),
        ),
    ]
