# Generated by Django 2.1.2 on 2018-11-07 21:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ödenen Ücret')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Muayene Tarihi')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
            },
        ),
        migrations.AlterModelOptions(
            name='threat',
            options={'verbose_name': 'Muayene', 'verbose_name_plural': 'Muayeneler'},
        ),
        migrations.AddField(
            model_name='threat',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Muayene Tarihi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='threat',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient', verbose_name='Hasta'),
        ),
    ]
